Post.create(:id => 1, :title => "Pentaho and Publishing Reports", :description => "Publishing reports using Pentaho and some of the quirks that go along with it.", :category_id => "2", :active => false)
Post.create(:id => 2, :title => "Rails and Simple Form Nested Attributes", :description => "How to associate things with the new params.require from rails 4.", :category_id => "3", :active => true)
Post.create(:id => 3, :title => "SSH Into a Remote MySQL Table Using Pentaho.", :description => "SSH Into Remote Tables and Do Some Things", :category_id => "2", :active => true)
Post.create(:id => 4, :title => "How It All Connects. The MEAN Stack.", :description => "Mean.io. A generator for a base MEAN stack app.", :category_id => "5", :active => false)
Post.create(:id => 5, :title => "Aggregating Numbers and Running Totals.", :description => "Aggregated + Daily Stats in same row. MySql. Running fields.", :category_id => "8", :active => false)
Post.create(:id => 6, :title => "Review of  Algorithms by Robert Sedgewick; Kevin Wayne", :description => "A short review of Algorithms by Robert Sedgewick. ", :category_id => "1", :active => false)
Post.create(:id => 7, :title => "Eloquent Ruby", :description => "A Review of Eloquent Ruby", :category_id => "1", :active => false)
Post.create(:id => 8, :title => "Review of Rails AntiPatterns: Best Practice Ruby on Rails Refactoring", :description => "A brief review of this delightful book.", :category_id => "1", :active => false)
Post.create(:id => 9, :title => "Learning Sass", :description => "A few tips n tricks n things from browsin the interwebs.", :category_id => "6", :active => false)
Post.create(:id => 10, :title => "Famo.us", :description => "Learning to use Famo.us to make minority report type cool looking UI's", :category_id => "7", :active => false)
Post.create(:id => 11, :title => "Mongodb Vs RDBMS", :category_id => "5", :active => false)
Post.create(:id => 12, :title => "Running Total by Groups and date", :category_id => "8", :active => false)
Post.create(:id => 13, :title => "Riding Rails with AngularJS", :description => "There are errors in this tutorial. Heres the fixes", :category_id => "7", :active => true)
Post.create(:id => 14, :title => "MEAN Stack ", :description => "Making a Show Route\r\n", :category_id => "5", :active => true)
Post.create(:id => 15, :title => "Easy Fix for File exists @ dir_s_mkdir Mina + Rails", :description => "Make sure that shared/tmp directory is created if not ssh into the server and\r\n\r\n", :category_id => "1", :active => true)
Post.create(:id => 16, :title => "Axlsx Error warning: previous definition of APP_PATH was here", :category_id => "3", :active => false)
Post.create(:id => 17, :title => "Active Admin and Rendering tables with Custom Sql", :category_id => "1", :active => false)
Post.create(:id => 18, :title => "Materialized Views", :description => "Speeding up with materialized views and such.", :category_id => "8", :active => false)
Post.create(:id => 19, :title => "Generating Sql Migrations in Rails", :description => "Rails SQL Queries for Procs,Events,and Tables", :category_id => "1", :active => false)
